// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package com.openshift.notebook.core.domain;

import java.util.Date;

public class NoteBuilder extends NoteBuilderBase<NoteBuilder> {
	public static NoteBuilder note() {
		return new NoteBuilder();
	}

	public NoteBuilder() {
		super(new Note());
	}

	public Note build() {
		return getInstance();
	}
}

class NoteBuilderBase<GeneratorT extends NoteBuilderBase<GeneratorT>> {
	private Note instance;

	protected NoteBuilderBase(Note aInstance) {
		instance = aInstance;
	}

	protected Note getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withId(String aValue) {
		instance.setId(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withTitle(String aValue) {
		instance.setTitle(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withText(String aValue) {
		instance.setText(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withCreated(Date aValue) {
		instance.setCreated(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withTags(String[] aValue) {
		instance.setTags(aValue);

		return (GeneratorT) this;
	}
}
