// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package com.openshift.notebook.core.domain;

import java.util.Date;

public class NotebookBuilder extends NotebookBuilderBase<NotebookBuilder> {
	public static NotebookBuilder notebook() {
		return new NotebookBuilder();
	}

	public NotebookBuilder() {
		super(new Notebook());
	}

	public Notebook build() {
		return getInstance();
	}
}

class NotebookBuilderBase<GeneratorT extends NotebookBuilderBase<GeneratorT>> {
	private Notebook instance;

	protected NotebookBuilderBase(Notebook aInstance) {
		instance = aInstance;
	}

	protected Notebook getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withName(String aValue) {
		instance.setName(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withDescription(String aValue) {
		instance.setDescription(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withCreated(Date aValue) {
		instance.setCreated(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withAuthor(String aValue) {
		instance.setAuthor(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withTags(String[] aValue) {
		instance.setTags(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withNotes(Note[] aValue) {
		instance.setNotes(aValue);

		return (GeneratorT) this;
	}
}
